language: java

jdk:
    - oraclejdk8

before_install:
    - chmod +x gradlew

install:
    - ./gradlew jmortar-core-persistence:assemble publishToMavenLocal
    - ./gradlew jmortar-core-persistence-hibernate:assemble
    - ./gradlew jmortar-core-persistence-dynamodb:assemble
